cd ~
mkdir DownloadBlockLists
cd DownloadBlockLists
wget https://raw.githubusercontent.com/herrbischoff/trackers/master/trackers.txt
wget https://raw.githubusercontent.com/herrbischoff/trackers/master/domains.txt
wget https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Ads
wget https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Apple
wget https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Bloat
wget https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Junk
wget https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Malware
wget https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Marketing
wget https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Microsoft
wget https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Risk
wget https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Scam
wget https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Suspicious
wget https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Top_Level
wget https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Tracking
wget https://raw.githubusercontent.com/anthony-wang/PiHoleBlocklist/master/hosts1.txt
wget https://raw.githubusercontent.com/anthony-wang/PiHoleBlocklist/master/hosts2.txt
wget https://raw.githubusercontent.com/anthony-wang/PiHoleBlocklist/master/hosts3.txt
wget https://raw.githubusercontent.com/gieljnssns/Social-media-Blocklists/master/pihole-instagram.txt
wget https://raw.githubusercontent.com/gieljnssns/Social-media-Blocklists/master/pihole-facebook.txt
wget https://raw.githubusercontent.com/gieljnssns/Social-media-Blocklists/master/pihole-tiktok.txt
wget https://raw.githubusercontent.com/gieljnssns/Social-media-Blocklists/master/pihole-whatsapp.txt
wget https://raw.githubusercontent.com/justdomains/blocklists/master/lists/easylist-justdomains.txt
wget https://raw.githubusercontent.com/justdomains/blocklists/master/lists/easyprivacy-justdomains.txt
wget https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/CountryCodesLists/Germany.txt
